# -*- coding: utf-8 -*-
"""Tarea_Electiva_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FBr-d6xluRWtjPFw2HsL-689DDFLIng
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-20,20,500)
y = x**2
plt.plot(x,y, color="g", label="$f(x)=X^2$", linewidth=2) #poner etiquetas a la variable linewidth cambia el grosor de la línea
#el signo $ $ sirve para poner el escrito en modo cursiva
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid() #que aparezca la cuadricula
plt.title("Función Cuadrática")
plt.savefig("x2.png") #comando para exportar el grafico IMPORTANTE PONER la extensión, sirve en .pdf, .png
plt.show()

x = np.linspace(-20,20,40)
y = x**2
plt.plot(x,y, "rx-", label="$f(x)=X^2$", linewidth=2) # despues de x,y según el comando que se agregue abra un estilo o no
#la primera letra es el color r=red, X=cruz o --=linea discontinua, s=square, y el tercero es si es linea
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid() #que aparezca la cuadricula
plt.title("Función Cuadrática")
plt.savefig("x2.png") #comando para exportar el grafico IMPORTANTE PONER la extensión, sirve en .pdf, .png
plt.show()

x = np.linspace(-20,20,40)
y = x**2
plt.plot(x,y, "ms", label="$f(x)=X^2$", linewidth=2) # despues de x,y según el comando que se agregue abra un estilo o no
#la primera letra es el color r=red, X=cruz o --=linea discontinua, s=square, y el tercero es si es linea
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid() #que aparezca la cuadricula
plt.title("Función Cuadrática")
plt.savefig("x2.png") #comando para exportar el grafico IMPORTANTE PONER la extensión, sirve en .pdf, .png
plt.show()

x = np.linspace(-20,20,40)
y = x**2
plt.plot(x,y, "gs--", label="$f(x)=X^2$", linewidth=2) # despues de x,y según el comando que se agregue abra un estilo o no
#la primera letra es el color r=red, X=cruz o --=linea discontinua, s=square, y el tercero es si es linea
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid() #que aparezca la cuadricula
plt.title("Función Cuadrática")
plt.savefig("x2.png") #comando para exportar el grafico IMPORTANTE PONER la extensión, sirve en .pdf, .png
plt.show()

x=[2,4,6,7,10,15] # numero de horas de estudio
y=[10,23,45,68,81,92] #puntaje de cada estudiante de cero a cien

plt.scatter(x,y, s=50, color="m", marker="^",alpha=0.5) #gráfico de correlación
# S es el tamaño del objeto, marker como se ve el,
plt.title("Horas de estudio VS Puntaje en un examen")
plt.xlabel("horas de estudio (horas)")
plt.ylabel("Puntaje (0-100)")
plt.grid()
plt.show()

x=np.linspace(0,10,100)
y=np.sin(x)
y2=np.cos(x)

plt.plot(x,y, "g--",label="$sen(x)$")
plt.plot(x,y2,"r:" ,label="$cos(x)$")
plt.title("Funcion seno y coseno")
plt.xlabel("X")
plt.grid()
plt.legend()
plt.show()

plt.subplot(2,1,1) #cantidad de filas, cantidad de columnas y la posición la figura
plt.plot(x,y, "m:", label = "$sen(x)$")
plt.title("Sen(x)")
plt.legend()

plt.subplot(2,1,2)
plt.plot(x,y2,"gx-", label = "$cos(x)$")
plt.title("Cos(x)")
plt.legend()

plt.subplot(1,2,1) #cantidad de filas, cantidad de columnas y la posición la figura
plt.plot(x,y, "b-", label = "$sen(x)$")
plt.title("Sen(x)")
plt.legend()

plt.subplot(1,2,2)
plt.plot(x,y2,"rx-", label = "$cos(x)$")
plt.title("Cos(x)")
plt.legend()